# Site
name: "Andrimo"
description: "All About Android."
meta_description: "All About Android, we provide free android help and latest android tricks, tips, latest smartphone, gadgets review and more.."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-135019824-1'
disqus: 'andrimo'
mailchimp-list: 'https://eepurl.com/gg6EE5'
include: ["_pages"]
permalink: /:title/
site.url: 'https://'

# Authors
authors:
  Team Andrimo:
    name: Team Andrimo
    display_name: Team Andrimo
    gravatar: f5114248b51ae98a7bbe5ef430c5a164
    email: team@andrimo.com
    web: https://www.andrimo.com
    twitter: https://twitter.com/andrimoblog
    description: "Author of Andrimo, A Offical Publisher of Andrimo. Publish Article on Weekly Basis"
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-admin
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
